"""phase3_ai_parsing

Revision ID: 1d4f8c5cb4bb
Revises: 7f2dede90e67
Create Date: 2026-07-11 18:15:32.072491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d4f8c5cb4bb'
down_revision: Union[str, None] = '7f2dede90e67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('expenses', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('expenses', sa.Column('order_id', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('expenses', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('is_subscription', sa.Boolean(), nullable=True))
    op.add_column('expenses', sa.Column('confidence_score', sa.Numeric(precision=3, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'confidence_score')
    op.drop_column('expenses', 'is_subscription')
    op.drop_column('expenses', 'discount')
    op.drop_column('expenses', 'tax')
    op.drop_column('expenses', 'items')
    op.drop_column('expenses', 'invoice_number')
    op.drop_column('expenses', 'order_id')
    op.drop_column('expenses', 'payment_method')
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
