"""add_junk_fees

Revision ID: c565b8406b08
Revises: d9baed3a6d8d
Create Date: 2026-07-20 13:07:32.803426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c565b8406b08'
down_revision: Union[str, None] = 'd9baed3a6d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('junk_fees', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'junk_fees')
    # ### end Alembic commands ###
