"""Add billing_cycle

Revision ID: d9baed3a6d8d
Revises: 6b84a6dbff0b
Create Date: 2026-07-20 12:26:47.924367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9baed3a6d8d'
down_revision: Union[str, None] = '6b84a6dbff0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('billing_cycle', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'billing_cycle')
    # ### end Alembic commands ###
